### ISSUE TITLE
请问不支持win7了吗？

### ISSUE THREAD

**Issue by pizixi** [tkzcfc/npipe#1]

**Comment by tkzcfc** [comment]
win7没试过  能在win7上编译就是支持吧

**Comment by pizixi** [comment]
测试了 用release下的window客户端在window7和server2008上都无法运行

**Comment by tkzcfc** [comment]
[np-v1.0.3-x86_64-win7-windows-msvc.zip](https://github.com/user-attachments/files/17177734/np-v1.0.3-x86_64-win7-windows-msvc.zip)
试试呢

**Comment by pizixi** [comment]
可以了，厉害，谢谢
