### ISSUE TITLE
请问使用tls私有证书如何使用

### ISSUE THREAD

**Issue by pizixi** [tkzcfc/npipe#2]
使用generate-certificate.sh生产了私有证书，服务端打开tls配置
{
	"database_url": "sqlite://data.db?mode=rwc",
	"listen_addr": "0.0.0.0:9988",
	"enable_tls": true,
	"tls_cert": "./cert.pem",
	"tls_key": "./server.key.pem",
	"web_base_dir": "./dist",
	"web_addr": "0.0.0.0:8120",
	"web_username": "admin",
	"web_password": "123456"
}

客户端使用命令：np_client.exe run -s ip:9988-u ceshi -p ceshipwd --enable-tls --ca-cert root-ca.pem

报错：72 +08:00[0m] [38;5;208mWARN[0m [C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\rustls-0.20.9\src\conn.rs:1332] [38;5;208mSending fatal alert BadCertificate[0m
72 +08:00[0m] [38;5;196mERROR[0m [np_client\src/main.rs:139] [38;5;196mpresented server name type wasn't supported[0m

**Comment by pizixi** [comment]
感觉这个项目很不错，能在服务端直接添加客户端之间的端口转发，很好用，目前IPerf3测试效率可能不是太好，希望能持续更新，另外自己弄了一个webui，https://github.com/pizixi/npipe-webui

**Comment by tkzcfc** [comment]
👍 生成证书的时候填的域名要和你客户端连接的地址一样  如果是IP地址就填IP

**Comment by pizixi** [comment]
> 👍 生成证书的时候填的域名要和你客户端连接的地址一样 如果是IP地址就填IP

使用ip好像也不太行，不太会玩了

**Comment by pizixi** [comment]
![image](https://github.com/user-attachments/assets/8016e57f-0c30-44ce-8efb-78b7ca84a522)
客户端的上传带宽吃不满

**Comment by tkzcfc** [comment]
这个和接收端数据处理速度也有关，并不是无脑往服务器上丢就完了  这样服务器内存会爆的
![image](https://github.com/user-attachments/assets/fd775408-16ef-4fcc-831a-c782b1cddcda)
![image](https://github.com/user-attachments/assets/c67404bd-c8a2-4871-a8ca-1233ad656130)

**Comment by tkzcfc** [comment]
测试可以把这个值改大  隧道不压缩 不进行任何加密

**Comment by tkzcfc** [comment]
也可以暂时把这段代码注释了

**Comment by tkzcfc** [comment]
加下QQ呢  2426898730  聊下具体测试细节

**Comment by pizixi** [comment]
加了
